sudo: false
language: node_js
node_js:
  - 9
  - 8
os:
  - linux
  - osx
cache: yarn
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
jobs:
  fast_finish: true
  include:
    - stage: release
      node_js: 9
      deploy:
        skip_cleanup: true
        provider: script
        script: npx travis-deploy-once "npx semantic-release"
      on:
        branch: master
